directory: ~/Music
library: ~/Music/library.db
plugins: convert scrub fetchart

#plugins: lastgenre fetchart scrub the

id3v23: yes
paths:
    default: Album/$albumartist/$album%aunique{}/$track $title
    singleton: Single/$artist_credit/$artist_credit - $title
    comp: %title{$albumtype}/$album%aunique{}/$track %left{$artist,20} - $title
convert:
    auto: yes
    max_bitrate: 192
    format: mp3
    command: ffmpeg -i $source -y -vn -aq 4 $dest
    languages: en
    embed: no
replace:
    '[\\/]': _
    ^\.: _
    '[\x00-\x1f]': _
    '[<>"\?\*\|]': _
    '[:]': ' - '
    \.$: _
    \s+$: ''
    ^\s+: ''
    ^-: _

fetchart:
    auto: yes
    maxwidth: 640
    cautious: true
    sources:
    - coverart
    - itunes
    - amazon
    - albumart
    - filesystem
